# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainFrame.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(360, 351)
        MainWindow.setAcceptDrops(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAcceptDrops(True)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEditPath = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditPath.setObjectName("lineEditPath")
        self.gridLayout.addWidget(self.lineEditPath, 6, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.butttomOpenFile = QtWidgets.QPushButton(self.centralwidget)
        self.butttomOpenFile.setObjectName("butttomOpenFile")
        self.gridLayout.addWidget(self.butttomOpenFile, 6, 1, 1, 1)
        self.buttomExportar = QtWidgets.QPushButton(self.centralwidget)
        self.buttomExportar.setObjectName("buttomExportar")
        self.gridLayout.addWidget(self.buttomExportar, 8, 0, 1, 3)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 0, 1, 1)
        self.spinnerTop = QtWidgets.QSpinBox(self.centralwidget)
        self.spinnerTop.setMinimum(1)
        self.spinnerTop.setMaximum(10)
        self.spinnerTop.setProperty("value", 3)
        self.spinnerTop.setDisplayIntegerBase(10)
        self.spinnerTop.setObjectName("spinnerTop")
        self.gridLayout.addWidget(self.spinnerTop, 3, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.spinnerCompartidos = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.spinnerCompartidos.setDecimals(1)
        self.spinnerCompartidos.setMinimum(0.0)
        self.spinnerCompartidos.setMaximum(1.0)
        self.spinnerCompartidos.setSingleStep(0.1)
        self.spinnerCompartidos.setProperty("value", 0.4)
        self.spinnerCompartidos.setObjectName("spinnerCompartidos")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinnerCompartidos)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.spinnerReacciones = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.spinnerReacciones.setDecimals(1)
        self.spinnerReacciones.setMaximum(1.0)
        self.spinnerReacciones.setSingleStep(0.1)
        self.spinnerReacciones.setProperty("value", 0.3)
        self.spinnerReacciones.setObjectName("spinnerReacciones")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinnerReacciones)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.spinnerComentarios = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.spinnerComentarios.setDecimals(1)
        self.spinnerComentarios.setMaximum(1.0)
        self.spinnerComentarios.setSingleStep(0.1)
        self.spinnerComentarios.setProperty("value", 0.3)
        self.spinnerComentarios.setObjectName("spinnerComentarios")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spinnerComentarios)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.spinnerInteracciones = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.spinnerInteracciones.setDecimals(1)
        self.spinnerInteracciones.setMaximum(1.0)
        self.spinnerInteracciones.setSingleStep(0.1)
        self.spinnerInteracciones.setProperty("value", 0.4)
        self.spinnerInteracciones.setObjectName("spinnerInteracciones")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinnerInteracciones)
        self.spinnerMatchAudience = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.spinnerMatchAudience.setDecimals(1)
        self.spinnerMatchAudience.setMaximum(1.0)
        self.spinnerMatchAudience.setSingleStep(0.1)
        self.spinnerMatchAudience.setProperty("value", 0.3)
        self.spinnerMatchAudience.setObjectName("spinnerMatchAudience")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinnerMatchAudience)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.spinnerEngagement = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.spinnerEngagement.setDecimals(1)
        self.spinnerEngagement.setMaximum(1.0)
        self.spinnerEngagement.setSingleStep(0.1)
        self.spinnerEngagement.setProperty("value", 0.2)
        self.spinnerEngagement.setObjectName("spinnerEngagement")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spinnerEngagement)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.spinnerAlcance = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.spinnerAlcance.setDecimals(1)
        self.spinnerAlcance.setMaximum(1.0)
        self.spinnerAlcance.setSingleStep(0.1)
        self.spinnerAlcance.setProperty("value", 0.1)
        self.spinnerAlcance.setObjectName("spinnerAlcance")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.spinnerAlcance)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.horizontalLayout.addWidget(self.groupBox)
        self.gridLayout.addLayout(self.horizontalLayout, 7, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 360, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Top:"))
        self.butttomOpenFile.setText(_translate("MainWindow", "..."))
        self.buttomExportar.setText(_translate("MainWindow", "Exportar excel con las estadísticas"))
        self.label_2.setText(_translate("MainWindow", "Facebook Excel:"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Índice interacciones"))
        self.label_7.setText(_translate("MainWindow", "Compartidos:"))
        self.label_9.setText(_translate("MainWindow", "Reacciones:"))
        self.label_8.setText(_translate("MainWindow", "Comentarios:"))
        self.groupBox.setTitle(_translate("MainWindow", "Índice mejor post"))
        self.label_5.setText(_translate("MainWindow", "Engagement:"))
        self.label_6.setText(_translate("MainWindow", "Alcance:"))
        self.label_4.setText(_translate("MainWindow", "Interacciones:"))
        self.label_3.setText(_translate("MainWindow", "Match Audience:"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
